# Generated by Django 2.0.6 on 2018-06-15 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descuento_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('descuento_monto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('isporcentaje', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='destino')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='itinerario')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('frase', models.TextField(blank=True, null=True)),
                ('duracion', models.PositiveSmallIntegerField()),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('portada', models.ImageField(upload_to='paquete')),
                ('imagen', models.ImageField(upload_to='paquete')),
                ('disponibilidad', models.PositiveSmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('isoferta', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Destino')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('descriobservaciones', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio_final', models.DecimalField(decimal_places=4, max_digits=14)),
                ('iscupon', models.BooleanField(default=False)),
                ('ispago', models.BooleanField(default=False)),
                ('fecpago', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecregistro', models.DateTimeField(auto_now_add=True)),
                ('fecactualizacion', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cupon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='viajes.Cupon')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Paquete')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Recurso'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='tag',
            field=models.ManyToManyField(to='viajes.Tag'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Paquete'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='isvalid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Paquete'),
        ),
    ]
