# Generated by Django 2.0.6 on 2018-06-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='fecha_fin',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='fecha_ini',
        ),
    ]
